services:
  postgres:
    image: postgres:14
    container_name: spring_auth_db
    environment:
      POSTGRES_USER: spring
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: spring-auth
    ports:
      - "5532:5432"

  spring_auth:
    image: spring-auth
    container_name: spring_auth
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/spring-auth
      SPRING_DATASOURCE_USERNAME: spring
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
