services:
  postgres:
    image: postgres:14
    container_name: spring_api_db
    environment:
      POSTGRES_USER: spring
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: spring-boot-jwt
    ports:
      - "5532:5432"

  spring_api:
    image: spring-boot-jwt
    container_name: spring_api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/spring-boot-jwt
      SPRING_DATASOURCE_USERNAME: spring
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
